apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streaming-nessie-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "streaming-nessie-db.labels" . | indent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  postgres-password: {{ .Values.auth.postgresPassword | quote }}
  database: {{ .Values.auth.database | quote }}
