apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-credentials
            key: access-key-id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: awssm-credentials
            key: secret-access-key
            namespace: external-secrets
          sessionTokenSecretRef:
            name: awssm-credentials
            key: session-token
            namespace: external-secrets
