apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storage-minio-credentials
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: platform-minio-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: root-user
      remoteRef:
        key: /spark-platform/dev/storage-minio
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: /spark-platform/dev/storage-minio
        property: root-password
