apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-metabase.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "streaming-metabase.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "streaming-metabase.name" . | quote }}
