apiVersion: v1
kind: Service
metadata:
  name: argocd-public
  namespace: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
