apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bi-trino.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bi-trino.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/name: {{ include "bi-trino.name" . | quote }}
  template:
    metadata:
      labels:
{{ include "bi-trino.labels" . | indent 8 }}
    spec:
      containers:
        - name: trino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /v1/info
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          volumeMounts:
            - name: trino-config
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-config
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: trino-catalogs
              mountPath: /etc/trino/catalog
            - name: trino-data
              mountPath: {{ .Values.trino.dataDir }}
      volumes:
        - name: trino-config
          configMap:
            name: {{ include "bi-trino.fullname" . }}-config
        - name: trino-catalogs
          configMap:
            name: {{ include "bi-trino.fullname" . }}-catalogs
{{- if .Values.persistence.enabled }}
        - name: trino-data
          persistentVolumeClaim:
            claimName: {{ include "bi-trino.fullname" . }}
{{- else }}
        - name: trino-data
          emptyDir: {}
{{- end }}
