apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secretmanager
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  provider:
    gcpsm:
      projectID: data-platform-prod-491113
