apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretmanager
  target:
    name: argocd-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: spark-platform-prod-argocd
