apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      path: charts/demo-app
      helm:
        releaseName: demo-app
        valueFiles:
          - $values/values/common/demo-apps.yaml
          - $values/values/dev/demo-apps.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
