apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-assets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/alexwlodek/gitops-data-platform.git
      targetRevision: main
      path: charts/logging-assets
      helm:
        releaseName: logging-assets
        valueFiles:
          - $values/values/common/logging-assets.yaml
          - $values/values/dev/logging-assets.yaml
    - repoURL: https://github.com/alexwlodek/gitops-data-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
