apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 66.2.1 # TODO: pin version
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/values/common/monitoring.yaml
          - $values/values/dev/monitoring.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
