apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 1.3.2
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/values/common/external-secrets.yaml
          - $values/values/dev/external-secrets.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
