apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-nessie-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  project: platform
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: storage-nessie-db
      namespace: apps
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/podManagementPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.apiVersion
        - .spec.volumeClaimTemplates[]?.kind
        - .spec.volumeClaimTemplates[]?.status
        - .spec.volumeClaimTemplates[]?.spec.volumeMode
  sources:
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      path: charts/storage-nessie-db
      helm:
        releaseName: storage-nessie-db
        valueFiles:
          - $values/values/common/storage-nessie-db.yaml
          - $values/values/dev/storage-nessie-db.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
