apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storage-nessie-db-credentials
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretmanager
  target:
    name: platform-nessie-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: spark-platform-prod-storage-nessie-db
