apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-grafana-admin-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secretmanager
  target:
    name: platform-grafana-admin
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: spark-platform-prod-monitoring-grafana
