apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: argocd-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: server.secretkey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/argocd
        metadataPolicy: None
        property: server-secretkey
    - secretKey: admin.password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/argocd
        metadataPolicy: None
        property: admin-password-bcrypt
    - secretKey: admin.passwordMtime
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/argocd
        metadataPolicy: None
        property: admin-password-mtime
