apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: storage-nessie-db-credentials
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: platform-nessie-db-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: database
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/storage-nessie-db
        metadataPolicy: None
        property: database
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/storage-nessie-db
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/storage-nessie-db
        metadataPolicy: None
        property: password
    - secretKey: postgres-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spark-platform/prod/storage-nessie-db
        metadataPolicy: None
        property: postgres-password
