#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=lib/terraform.sh
source "${SCRIPT_DIR}/lib/terraform.sh"

apply_prod_env_defaults

TERRAFORM_ENV_ROOT_DIR="${TERRAFORM_ENV_ROOT_DIR:-$(repo_root)/infra/envs/${DEPLOY_ENV}}"
TERRAFORM_NETWORK_DIR="${TERRAFORM_NETWORK_DIR:-${TERRAFORM_ENV_ROOT_DIR}/00-network}"
TERRAFORM_GKE_DIR="${TERRAFORM_GKE_DIR:-${TERRAFORM_ENV_ROOT_DIR}/10-gke}"
TERRAFORM_SHARED_SERVICES_DIR="${TERRAFORM_SHARED_SERVICES_DIR:-${TERRAFORM_ENV_ROOT_DIR}/20-shared-services}"
TERRAFORM_GCP_ROOT_DIR="${TERRAFORM_GCP_ROOT_DIR:-${TERRAFORM_ENV_ROOT_DIR}}"
TERRAFORM_GCP_NETWORK_DIR="${TERRAFORM_GCP_NETWORK_DIR:-${TERRAFORM_NETWORK_DIR}}"
TERRAFORM_GCP_GKE_DIR="${TERRAFORM_GCP_GKE_DIR:-${TERRAFORM_GKE_DIR}}"
TERRAFORM_GCP_PLATFORM_DIR="${TERRAFORM_GCP_PLATFORM_DIR:-${TERRAFORM_SHARED_SERVICES_DIR}}"
TERRAFORM_GCP_DIR="${TERRAFORM_GCP_DIR:-${TERRAFORM_GCP_GKE_DIR}}"

PUBLIC_GATEWAY_IP_ADDRESS="${PUBLIC_GATEWAY_IP_ADDRESS:-$(terraform_output_raw_if_exists "${TERRAFORM_NETWORK_DIR}" public_gateway_ip_address)}"

export SCRIPT_DIR
export REPO_ROOT
export TERRAFORM_ENV_ROOT_DIR
export TERRAFORM_NETWORK_DIR
export TERRAFORM_GKE_DIR
export TERRAFORM_SHARED_SERVICES_DIR
export TERRAFORM_GCP_ROOT_DIR
export TERRAFORM_GCP_NETWORK_DIR
export TERRAFORM_GCP_GKE_DIR
export TERRAFORM_GCP_PLATFORM_DIR
export TERRAFORM_GCP_DIR
export PROJECT_ID
export REGION
export CLUSTER_NAME
export PUBLIC_GATEWAY_IP_NAME
export PUBLIC_GATEWAY_IP_ADDRESS
export KUBE_CONTEXT
