apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storage-nessie.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "storage-nessie.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/name: {{ include "storage-nessie.name" . | quote }}
  template:
    metadata:
      labels:
{{ include "storage-nessie.labels" . | indent 8 }}
    spec:
      containers:
        - name: nessie
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: management
              containerPort: {{ .Values.service.managementPort }}
          env:
            - name: QUARKUS_HTTP_PORT
              value: {{ .Values.service.port | quote }}
            - name: QUARKUS_MANAGEMENT_PORT
              value: {{ .Values.service.managementPort | quote }}
            - name: NESSIE_VERSION_STORE_TYPE
              value: {{ .Values.nessie.versionStoreType | quote }}
            - name: NESSIE_VERSION_STORE_DEFAULT_BRANCH
              value: {{ .Values.nessie.defaultBranch | quote }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "storage-nessie.fullname" . }}
                  key: db-username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "storage-nessie.fullname" . }}
                  key: db-password
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: management
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: management
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
