apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storage-nessie.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "storage-nessie.labels" . | indent 4 }}
type: Opaque
stringData:
  db-username: {{ .Values.database.username | quote }}
  db-password: {{ .Values.database.password | quote }}
