apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: platform
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: elasticsearch-master
      namespace: logging
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/revisionHistoryLimit
        - /spec/template/metadata/annotations
        - /spec/template/spec/affinity/nodeAffinity
        - /spec/template/spec/affinity/podAffinity
        - /spec/template/spec/affinity/podAntiAffinity
        - /spec/template/spec/containers/0/env/1/valueFrom/fieldRef/apiVersion
        - /spec/template/spec/containers/0/ports/0/protocol
        - /spec/template/spec/containers/0/ports/1/protocol
        - /spec/template/spec/containers/0/terminationMessagePath
        - /spec/template/spec/containers/0/terminationMessagePolicy
        - /spec/template/spec/dnsPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/securityContext/supplementalGroups
        - /spec/template/spec/securityContext/sysctls
        - /spec/template/spec/serviceAccount
        - /spec/template/spec/terminationGracePeriodSeconds
        - /spec/template/spec/volumes/1/configMap/defaultMode
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/spec/volumeMode
        - /spec/volumeClaimTemplates/0/status
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: elasticsearch
      targetRevision: 20.0.4
      helm:
        releaseName: elasticsearch
        valueFiles:
          - $values/values/common/logging-elasticsearch.yaml
          - $values/values/prod/logging-elasticsearch.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
