apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-public-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      path: charts/platform-public-gateway
      helm:
        releaseName: platform-public-gateway
        valueFiles:
          - $values/values/common/public-gateway.yaml
          - $values/values/prod/public-gateway.yaml
    - repoURL: https://github.com/alexwlodek/spark-platform-k8s.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
