apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: platform
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.19.3
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/values/common/cert-manager.yaml
          - $values/values/prod/cert-manager.yaml
    - repoURL: https://github.com/alexwlodek/gitops-data-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
