apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-nessie
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "33"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/alexwlodek/gitops-data-platform.git
      targetRevision: main
      path: charts/storage-nessie
      helm:
        releaseName: storage-nessie
        valueFiles:
          - $values/values/common/storage-nessie.yaml
          - $values/values/prod/storage-nessie.yaml
    - repoURL: https://github.com/alexwlodek/gitops-data-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
